# 作業目標:

    通過建立多層的神經網路, 了解權值矩陣更新

# 作業重點: 

3  層神經網路

通過增加更多的中間層，以對更多關係的組合進行建模

syn1 權值矩陣將隱層的組合輸出映射到最終結果，

而在更新 syn1 的同時，還需要更新 syn0 權值矩陣，

以從輸入資料中更好地產生這些組合

In [56]:
import numpy as np
# Sigmoid 函數可以將任何值都映射到一個位於 0 到  1 範圍內的值。通過它，我們可以將實數轉化為概率值
def nonlin(x, deriv=False):
    if(deriv==True):
        return x*(1-x)
    return 1/(1+np.exp(-x))

X = np.array([  [0,0,1],
                [0,1,1],
                [1,0,1],
                [1,1,1] ])  
        
# define y for output dataset            
y = np.array([[0, 0, 1, 1]]).T
X.shape, y.shape

((4, 3), (4, 1))

In [57]:
# seed random numbers to make calculation
# deterministic (just a good practice)
np.random.seed(1)
#亂數設定產生種子得到的權重初始化集仍是隨機分佈的，但每次開始訓練時，得到的權重初始集分佈都是完全一致的。
 
# initialize weights randomly with mean 0
syn0 = 2 * np.random.random((3,3)) - 1
# define syn1
syn1 = 2 * np.random.random((3,1)) - 1

iter = 0
#該神經網路權重矩陣的初始化操作。
#用 “syn0” 來代指 (即“輸入層-第一層隱層”間權重矩陣）
#用 “syn1” 來代指 (即“輸入層-第二層隱層”間權重矩陣)
syn0, syn1, syn0.shape, syn1.shape

(array([[-0.16595599,  0.44064899, -0.99977125],
        [-0.39533485, -0.70648822, -0.81532281],
        [-0.62747958, -0.30887855, -0.20646505]]), array([[ 0.07763347],
        [-0.16161097],
        [ 0.370439  ]]), (3, 3), (3, 1))

神經網路訓練
for 迴圈反覆運算式地多次執行訓練代碼，使得我們的網路能更好地擬合訓練集

In [99]:
for iter in range(10000):
    # forward propagation
    l0 = X
    #print(l0)
    #print(syn0)
    l1 = nonlin(np.dot(l0, syn0))
    #print(l1)
    #print(syn1)
    l2 = nonlin(np.dot(l1, syn1))
    #print(l2)
    l2_error = y - l2
    #print(l2_error)
    l2_delta = l2_error * nonlin(l2, True)
    #print(l2_delta)
    #print(syn1)
    l1_error = np.dot(l2_delta, syn1.T)
    #print(l1_error)
    l1_delta = l1_error * nonlin(l1, True)

    # update weights
    syn0 += np.dot(l0.T, l1_delta)
    # syn1 update weights
    syn1 += np.dot(l1.T, l2_delta)

print("Output After Training:")
print(l1)
print(l2)

Output After Training:
[[0.42293691 0.1591666  0.88413084]
 [0.34068177 0.11672212 0.88593397]
 [0.17662485 0.94338949 0.06011549]
 [0.13136848 0.92084494 0.06112462]]
[[0.00553165]
 [0.00466738]
 [0.99462517]
 [0.99412742]]
